FROM python:3.12-slim-bookworm AS base

WORKDIR /app

# instalando dependências
RUN apt-get update && apt-get install -y \
    libnsl2 \
    libaio1 \
    && rm -rf /var/lib/apt/lists/*

# copiando o uv para o estágio final
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

# copia os arquivos do projeto para o container
COPY . .

ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_HOST
ARG DB_PORT
ARG POSTGRES_DB


ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV POSTGRES_DB=${POSTGRES_DB}
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# inicia o container de desenvolvimento
CMD ["tail", "-f", "/dev/null"]
